### ISSUE TITLE
Status of adapter

### ISSUE THREAD

**Issue by bkazi** [aweary/preact-enzyme-adapter#1]
Since enzyme v3 has officially launched I was wondering if this project is still in development since it would be very useful
Are there any docs for what is expected of enzyme adapters?

**Comment by just-boris** [comment]
Any updates there?

The [current Preact documentation](https://preactjs.com/guide/unit-testing-with-enzyme) shows a way for Enzyme v2, but this package seems to be working with Enzyme v3. At least I have tested this in my Preact app, all `mount`, `shallow`, `render` methods are working well.

**Comment by aweary** [comment]
https://github.com/aweary/preact-enzyme-adapter/pull/6 provided a base implementation. I handed over control of the repo to the PR's author, @awinogradov. I don't have any time to work on this, so I'm happy to hand it over to someone who does.
