### ISSUE TITLE
Current state of this library

### ISSUE THREAD

**Issue by ergun1017** [aweary/preact-enzyme-adapter#9]
Hey,

What is the current state of this adapter? I couldn't find any other adapter implementation for `preact` 😞

Will this be maintained and published on npm?

Thank you!

**Comment by awinogradov** [comment]
Hi @ergun1017! I'm still waiting when @aweary makes me an owner of npm package.

**Comment by awinogradov** [comment]
Long conversation is here https://github.com/aweary/preact-enzyme-adapter/pull/7

**Comment by ergun1017** [comment]
Great! Looking forward to it!

**Comment by aweary** [comment]
I've added you as an owner @awinogradov
